name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #가장 최신 ubuntu에서 실행
    runs-on: ubuntu-latest

    steps:
    #actions/checkout을 사용 -> repository에서 소스코드 가져옴
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
